export {
  BURNOUT_RISK_DIAGNOSIS,
  INTROVERT_LEVEL_DIAGNOSIS,
  JA_NEKO_DIAGNOSIS,
  RUBEL_ACTIVE_DIAGNOSIS_KEY,
  RUBEL_LOCAL_CATALOG_KEY,
  SAMPLE_CAT_DOG_DIAGNOSIS,
  SEED_DIAGNOSES,
} from "@/lib/rubel/seedDiagnoses";
