import { defineTraitProfile } from "@/lib/specialty/traitProfile";
import type { SpecialtyCArchetypeSeed, SpecialtyCountryId } from "@/lib/specialty/types";

const tp = defineTraitProfile;

type CountryCArchetypeMap = Readonly<
  Record<
    Exclude<SpecialtyCountryId, "jp" | "fr" | "uk">,
    readonly SpecialtyCArchetypeSeed[]
  >
>;

export const REMAINING_COUNTRY_C_ARCHETYPES: CountryCArchetypeMap = {
  us: [
    {
      id: "lc-us-scale-architect",
      title: "スケール設計者",
      subtitle: "仕組みを広げ、実用性で価値を生む戦略型",
      analysis:
        "あなたは拡張性を先に設計し、短期成果と長期効率のバランスを取る力があります。",
      themeColor: "#D97706",
      affirmationLine: "あなたの設計が、チームの射程を一気に広げます。",
      traitProfile: tp({
        trait_conscientiousness: 0.8,
        trait_extraversion: 0.6,
        trait_openness: 0.6,
        trait_agreeableness: 0.35,
        trait_empathy: 0.3,
        trait_neuroticism: 0.2,
      }),
    },
    {
      id: "lc-us-field-pioneer",
      title: "原野の開拓者",
      subtitle: "未知の領域に最初の一歩を踏み出す行動型",
      analysis: "あなたは不確実性を恐れず、現場で学びながら前進するスタイルです。",
      themeColor: "#F59E0B",
      affirmationLine: "あなたの一歩が、新しい可能性の扉を開きます。",
      traitProfile: tp({
        trait_extraversion: 0.8,
        trait_openness: 0.8,
        trait_conscientiousness: 0.45,
        trait_agreeableness: 0.4,
        trait_empathy: 0.35,
        trait_neuroticism: 0.25,
      }),
    },
    {
      id: "lc-us-yield-optimizer",
      title: "収穫最適化者",
      subtitle: "データと効率で成果を最大化する実務型",
      analysis: "あなたは無駄を削ぎ、再現可能な高い成果を積み上げるタイプです。",
      themeColor: "#B45309",
      affirmationLine: "あなたの最適化が、持続可能な成長を支えます。",
      traitProfile: tp({
        trait_conscientiousness: 0.85,
        trait_openness: 0.5,
        trait_extraversion: 0.4,
        trait_agreeableness: 0.4,
        trait_empathy: 0.3,
        trait_neuroticism: 0.15,
      }),
    },
    {
      id: "lc-us-belt-connector",
      title: "ベルトの連結者",
      subtitle: "人と資源をつなぎ、拡大を支える調整型",
      analysis: "あなたはネットワークを活かし、個の力を組織の力に変える力があります。",
      themeColor: "#FBBF24",
      affirmationLine: "あなたのつなぎが、全体の推進力になります。",
      traitProfile: tp({
        trait_extraversion: 0.7,
        trait_agreeableness: 0.65,
        trait_empathy: 0.5,
        trait_openness: 0.5,
        trait_conscientiousness: 0.45,
        trait_neuroticism: 0.2,
      }),
    },
  ],
  ca: [
    {
      id: "lc-ca-sap-keeper",
      title: "樹液の守り手",
      subtitle: "自然の周期を読み、丁寧に収穫する忍耐型",
      analysis: "あなたは焦らず環境のリズムに合わせ、質を守りながら進めるタイプです。",
      themeColor: "#B45309",
      affirmationLine: "あなたの丁寧さが、春の再生力を育てます。",
      traitProfile: tp({
        trait_conscientiousness: 0.75,
        trait_empathy: 0.65,
        trait_agreeableness: 0.7,
        trait_openness: 0.45,
        trait_extraversion: 0.3,
        trait_neuroticism: 0.2,
      }),
    },
    {
      id: "lc-ca-spring-messenger",
      title: "春告げの伝令",
      subtitle: "季節の変化を共有し、希望を広げる共感型",
      analysis:
        "あなたは厳冬のあとに訪れる回復を人に届け、場の空気を温める力があります。",
      themeColor: "#D97706",
      affirmationLine: "あなたの言葉が、次の一歩を軽くします。",
      traitProfile: tp({
        trait_empathy: 0.8,
        trait_agreeableness: 0.75,
        trait_extraversion: 0.5,
        trait_openness: 0.5,
        trait_conscientiousness: 0.4,
        trait_neuroticism: 0.2,
      }),
    },
    {
      id: "lc-ca-forest-partner",
      title: "森の協働者",
      subtitle: "共有と配慮で持続可能な収穫を支える調和型",
      analysis: "あなたは共同体の利益を見据え、無理のない協力関係を築くタイプです。",
      themeColor: "#EA580C",
      affirmationLine: "あなたの協働が、長く続く信頼を生みます。",
      traitProfile: tp({
        trait_agreeableness: 0.8,
        trait_empathy: 0.7,
        trait_conscientiousness: 0.55,
        trait_openness: 0.45,
        trait_extraversion: 0.4,
        trait_neuroticism: 0.15,
      }),
    },
    {
      id: "lc-ca-cycle-reader",
      title: "周期の読み手",
      subtitle: "寒暖差から最適なタイミングを見極める観察型",
      analysis: "あなたは微細な変化に敏感で、環境に合わせた判断が得意です。",
      themeColor: "#F59E0B",
      affirmationLine: "あなたの感覚が、いちばん美しいタイミングを導きます。",
      traitProfile: tp({
        trait_openness: 0.65,
        trait_empathy: 0.6,
        trait_conscientiousness: 0.6,
        trait_agreeableness: 0.5,
        trait_extraversion: 0.3,
        trait_neuroticism: 0.2,
      }),
    },
  ],
  br: [
    {
      id: "lc-br-estate-builder",
      title: "農園の築き手",
      subtitle: "豊かな土壌で持続可能な基盤を育てる建設型",
      analysis: "あなたは長期視点で環境と人を育て、安定した成果を積み上げます。",
      themeColor: "#047857",
      affirmationLine: "あなたの基盤づくりが、未来の豊かさを支えます。",
      traitProfile: tp({
        trait_conscientiousness: 0.75,
        trait_extraversion: 0.55,
        trait_openness: 0.55,
        trait_agreeableness: 0.5,
        trait_empathy: 0.45,
        trait_neuroticism: 0.2,
      }),
    },
    {
      id: "lc-br-rhythm-spreader",
      title: "リズムの伝播者",
      subtitle: "活気を広げ、多様性を歓迎する情熱型",
      analysis: "あなたは人と文化をつなぎ、現場にエネルギーを届ける力があります。",
      themeColor: "#059669",
      affirmationLine: "あなたの熱量が、チームの創造性を引き出します。",
      traitProfile: tp({
        trait_extraversion: 0.8,
        trait_openness: 0.75,
        trait_empathy: 0.6,
        trait_agreeableness: 0.55,
        trait_conscientiousness: 0.35,
        trait_neuroticism: 0.3,
      }),
    },
    {
      id: "lc-br-soil-listener",
      title: "土壌の傾聴者",
      subtitle: "大地の声を読み、個性を引き出す感性型",
      analysis: "あなたは素材と環境の相性を見極め、独自の価値を生み出すタイプです。",
      themeColor: "#10B981",
      affirmationLine: "あなたの感性が、隠れた可能性を照らします。",
      traitProfile: tp({
        trait_openness: 0.7,
        trait_empathy: 0.65,
        trait_conscientiousness: 0.5,
        trait_agreeableness: 0.5,
        trait_extraversion: 0.4,
        trait_neuroticism: 0.25,
      }),
    },
    {
      id: "lc-br-harvest-host",
      title: "収穫のホスト",
      subtitle: "成果を分かち合い、共同体を育てるもてなし型",
      analysis: "あなたは成果を独占せず、周囲と喜びを共有するスタイルです。",
      themeColor: "#34D399",
      affirmationLine: "あなたのもてなしが、輪をどんどん広げます。",
      traitProfile: tp({
        trait_agreeableness: 0.75,
        trait_empathy: 0.7,
        trait_extraversion: 0.6,
        trait_openness: 0.5,
        trait_conscientiousness: 0.4,
        trait_neuroticism: 0.2,
      }),
    },
  ],
  cl: [
    {
      id: "lc-cl-resource-strategist",
      title: "資源の戦略家",
      subtitle: "安定と効率を両立する実務型リーダー",
      analysis: "あなたは基盤を固めつつ、長期の収益構造を設計する力があります。",
      themeColor: "#B91C1C",
      affirmationLine: "あなたの戦略が、長期戦の勝ち筋を作ります。",
      traitProfile: tp({
        trait_conscientiousness: 0.8,
        trait_openness: 0.55,
        trait_extraversion: 0.45,
        trait_agreeableness: 0.4,
        trait_empathy: 0.35,
        trait_neuroticism: 0.15,
      }),
    },
    {
      id: "lc-cl-isolation-guardian",
      title: "隔離地形の守護者",
      subtitle: "独自性を守り、差別化を維持する保護型",
      analysis: "あなたは環境の制約を強みに変え、他にはない価値を育てるタイプです。",
      themeColor: "#DC2626",
      affirmationLine: "あなたの守りが、唯一無二の個性を支えます。",
      traitProfile: tp({
        trait_conscientiousness: 0.7,
        trait_openness: 0.7,
        trait_empathy: 0.45,
        trait_agreeableness: 0.4,
        trait_extraversion: 0.35,
        trait_neuroticism: 0.2,
      }),
    },
    {
      id: "lc-cl-andes-navigator",
      title: "アンデス航路の導き手",
      subtitle: "二面性を行き来し、最適解を選ぶ柔軟型",
      analysis: "あなたは実務と創造を切り替えながら、状況に応じた判断が得意です。",
      themeColor: "#EF4444",
      affirmationLine: "あなたの柔軟性が、複雑な局面を乗り越えます。",
      traitProfile: tp({
        trait_openness: 0.75,
        trait_conscientiousness: 0.65,
        trait_extraversion: 0.5,
        trait_agreeableness: 0.45,
        trait_empathy: 0.4,
        trait_neuroticism: 0.2,
      }),
    },
    {
      id: "lc-cl-export-curator",
      title: "輸出のキュレーター",
      subtitle: "価値を世界向けに翻訳する編集型",
      analysis: "あなたはローカルの強みを外向きに伝え、魅力を再構成する力があります。",
      themeColor: "#F87171",
      affirmationLine: "あなたの翻訳が、価値を世界へ届けます。",
      traitProfile: tp({
        trait_extraversion: 0.6,
        trait_openness: 0.7,
        trait_empathy: 0.55,
        trait_agreeableness: 0.5,
        trait_conscientiousness: 0.5,
        trait_neuroticism: 0.25,
      }),
    },
  ],
  md: [
    {
      id: "lc-md-cellar-archivist",
      title: "セラーアーキビスト",
      subtitle: "時間を蓄積し、記録で価値を守る継承型",
      analysis: "あなたは目に見えない資産を大切にし、長期保管の品質を維持します。",
      themeColor: "#7E22CE",
      affirmationLine: "あなたの記録が、歴史の連続性を守ります。",
      traitProfile: tp({
        trait_conscientiousness: 0.85,
        trait_openness: 0.5,
        trait_empathy: 0.55,
        trait_agreeableness: 0.5,
        trait_extraversion: 0.25,
        trait_neuroticism: 0.2,
      }),
    },
    {
      id: "lc-md-resilience-keeper",
      title: "耐性の継承者",
      subtitle: "困難を越えて文化を守り抜く不屈型",
      analysis: "あなたは逆境でも芯を曲げず、共同体の記憶を未来へ渡す力があります。",
      themeColor: "#9333EA",
      affirmationLine: "あなたの信念が、次の世代の支えになります。",
      traitProfile: tp({
        trait_conscientiousness: 0.75,
        trait_empathy: 0.7,
        trait_agreeableness: 0.6,
        trait_openness: 0.55,
        trait_extraversion: 0.3,
        trait_neuroticism: 0.25,
      }),
    },
    {
      id: "lc-md-limestone-engineer",
      title: "石灰岩の設計者",
      subtitle: "地下空間を活かし、熟成環境を整える技術型",
      analysis: "あなたはインフラとプロセスを設計し、安定した熟成を可能にします。",
      themeColor: "#A855F7",
      affirmationLine: "あなたの設計が、時間の価値を高めます。",
      traitProfile: tp({
        trait_conscientiousness: 0.8,
        trait_openness: 0.6,
        trait_extraversion: 0.3,
        trait_agreeableness: 0.4,
        trait_empathy: 0.4,
        trait_neuroticism: 0.15,
      }),
    },
    {
      id: "lc-md-heritage-voice",
      title: "遺産の語り部",
      subtitle: "歴史を物語に変え、誇りを共有する文化型",
      analysis: "あなたは過去の意味を現代に翻訳し、人の心に届ける力があります。",
      themeColor: "#C084FC",
      affirmationLine: "あなたの物語が、文化の灯りをともします。",
      traitProfile: tp({
        trait_empathy: 0.75,
        trait_openness: 0.65,
        trait_agreeableness: 0.65,
        trait_extraversion: 0.45,
        trait_conscientiousness: 0.45,
        trait_neuroticism: 0.2,
      }),
    },
  ],
  pk: [
    {
      id: "lc-pk-aroma-curator",
      title: "香りの調律者",
      subtitle: "繊細な差異を見極め、体験価値を高める感性型",
      analysis: "あなたは品質の微差に敏感で、記憶に残る体験を設計する力があります。",
      themeColor: "#C2410C",
      affirmationLine: "あなたの感性が、特別な香りの記憶を生みます。",
      traitProfile: tp({
        trait_openness: 0.7,
        trait_empathy: 0.7,
        trait_conscientiousness: 0.55,
        trait_agreeableness: 0.55,
        trait_extraversion: 0.4,
        trait_neuroticism: 0.2,
      }),
    },
    {
      id: "lc-pk-hospitality-prince",
      title: "もてなしのプリンス",
      subtitle: "誇りと温かさで客人を迎える接待型",
      analysis: "あなたは相手の安心と喜びを最優先にし、文化を体験として届けます。",
      themeColor: "#EA580C",
      affirmationLine: "あなたのおもてなしが、心に深い余韻を残します。",
      traitProfile: tp({
        trait_empathy: 0.85,
        trait_agreeableness: 0.8,
        trait_extraversion: 0.5,
        trait_openness: 0.5,
        trait_conscientiousness: 0.45,
        trait_neuroticism: 0.15,
      }),
    },
    {
      id: "lc-pk-earth-archivist",
      title: "大地の記録者",
      subtitle: "古層の物語を現代に接続する継承型",
      analysis: "あなたは自然資源の意味を言語化し、価値を守るタイプです。",
      themeColor: "#F97316",
      affirmationLine: "あなたの記録が、大地の記憶を未来へつなぎます。",
      traitProfile: tp({
        trait_conscientiousness: 0.7,
        trait_openness: 0.6,
        trait_empathy: 0.6,
        trait_agreeableness: 0.55,
        trait_extraversion: 0.35,
        trait_neuroticism: 0.2,
      }),
    },
    {
      id: "lc-pk-grain-artisan",
      title: "粒の職人",
      subtitle: "一粒の個性を丁寧に仕上げる精密型",
      analysis: "あなたは細部まで丁寧に向き合い、品質の一貫性を守る力があります。",
      themeColor: "#FB923C",
      affirmationLine: "あなたの手仕事が、品質の信頼を育てます。",
      traitProfile: tp({
        trait_conscientiousness: 0.8,
        trait_openness: 0.5,
        trait_empathy: 0.5,
        trait_agreeableness: 0.5,
        trait_extraversion: 0.3,
        trait_neuroticism: 0.15,
      }),
    },
  ],
};
